### ISSUE TITLE
Add support xCode 8

### ISSUE THREAD

**Issue by mvyrko** [marmelroy/Zip#30]
Now, I'm working in xCode 8 and your pod is unbuildable.

**Comment by mostafaberg** [comment]
Just to weigh in , came here to open an issue to the same problem, I have sent now two PRs for each new version of Swift in XCode 8, you might be able to update your podFile to use those "branches" somehow to use it, it works locally for me, notice the Travis testing fails, but that's only because travis is building on XCode 7 not 8, tests pass locally on XCode 8

[Swift 2.3 PR](https://github.com/marmelroy/Zip/pull/33)
[Swift 3 PR](https://github.com/marmelroy/Zip/pull/34)

**Comment by mvyrko** [comment]
Thank you

**Comment by suchtomwow** [comment]
+1 to this. [This blog post](http://www.jessesquires.com/migrating-to-swift-3/) contains helpful tips for migrating open source libraries.

**Comment by nick3389** [comment]
pod 'Zip', :git => 'https://github.com/marmelroy/Zip.git', :branch => 'swift2.3'

is this ok?

**Comment by marmelroy** [comment]
Official Swift 3 version released as 0.5.
