### ISSUE TITLE
Execute bit is lost

### ISSUE THREAD

**Issue by jssuttles** [marmelroy/Zip#72]
Just stumbled on this as the only Swift cocoapod that works with my application. My only issue is that it strips the execute bits when it unzips. I have a zip with a .app inside. After unzipping, I get something like this guy does: http://apple.stackexchange.com/questions/181026/lsopenurlswithrole-failed-with-error-10810-cant-open-install-os-x-yosemite

When I mark everything as executable, the .app works again. That's not a very clean solution. I'm wondering if I missed something.

Below is my usage:
```swift
try Zip.unzipFile(location, destination: applicationsDirectory, overwrite: true, password: nil, progress: { (progress) -> () in
                print(progress)
                DispatchQueue.main.async {
                    self.downloadProgressBar.doubleValue = progress * 0.2 + 0.8;
                }
            }) // Unzip
```
Any help is much appreciated.

**Comment by mostafaberg** [comment]
@jssuttles how did you zip the file in the first place ? did you rememer to zip it and retain permissions ?

**Comment by jssuttles** [comment]
Thanks for getting back to me so quickly.
I know that I zipped it with the archive utility. When I unzip it with the archive utility, it is still runnable. When Zip unzips it, it's unrunnable.

**Comment by mostafaberg** [comment]
The thing is probably tools like archive utility has it's way of preserving meta info and recreating it automatically after extraction, since Zip itself doesn't preserve that, I'm looking into it to find out if there is a possibility to do that, if that's not the case then what you need to look for is the adding the feature to `minzip`, which this library uses

**Comment by mostafaberg** [comment]
I was wrong, seems like file information is being preserved after all, [see here](https://github.com/marmelroy/Zip/blob/master/Zip/minizip/unzip.c#L982-L983)

I'm not sure where this gets lost in the process, BTW, have you tried creating the Zip file using the library instead of an external tool ? just curious to see how this works

**Comment by mostafaberg** [comment]
Yep, seems like file permissions aren't retained by the `Zip` library and not `minizip` as i suspected, this is an issue in the library, I'm quite busy at work this coming few days so I can't really contribute as soon as i'd like, but the issue seems to reside in [this area](https://github.com/marmelroy/Zip/blob/master/Zip/Zip.swift#L167-L198) if you can take a look and submit a PR that would be great.

if not i'll eventually get to it, or maybe @marmelroy can look and advise!

**Comment by jssuttles** [comment]
Thanks for looking into it. I'll try both of your recommendations and get back to you later. (My open source contribution is close to nil so far, so I wouldn't expect much.)

**Comment by mostafaberg** [comment]
it was simpler than I initially thought so i made a fix for it that you can [find here](https://github.com/marmelroy/Zip/pull/73)

Give it a try and see if it works out for you, i've added a unit test for this case to avoid future issues, hopefully someone will accept the PR and it'll be available soon 👍

**Comment by jssuttles** [comment]
YES!!! It works splendidly. Thanks again. I guess we'll close this when it gets pulled.

**Comment by marmelroy** [comment]
Thanks @mostafaberg and @jssuttles. Fix is merged on master and will be in the next release.
