### ISSUE TITLE
Please help! Getting error no such module 'minizip' during builds

### ISSUE THREAD

**Issue by jlaurence2020** [marmelroy/Zip#86]
Hello all,

I am trying to incorporate this library into my project and my pod reference looks like this below:

pod 'Zip', git: 'https://github.com/marmelroy/Zip', branch: ‘master’, submodules: true

However, when my swift 3.0 source uses import minizip, I get the following error.

**Comment by juxs** [comment]
I get the same error. "Missing required module 'minizip'"
I'm developing a Swift framework with a wrapped c library and the client project can't find the sub module. So I tried Zip but no luck either.
Not using cocoapods but manual setup.

**Comment by mostafaberg** [comment]
Can you create an example project that reproduces this error so we can help ?
also, can you mention your cocoapods and Xcode versions ?

**Comment by mostafaberg** [comment]
@juxs You are having a different issue, please open a new issue and we can take it from there.

**Comment by therabbitwindfall** [comment]
juxs, here is how to solve:
1) Create folder "minizip\aes"
2) Copy *.* from https://github.com/nmoinvaz/minizip/tree/master/aes to yours one from step 1
3) Copy crypt.h, ioapi.c, ioapi.h, module.modulemap, unzip.c, unzip.h, zip.c, zip.h from https://github.com/nmoinvaz/minizip to yours minizip root

**Comment by kabilan-baskaran** [comment]
@mostafaberg , i am getting the same issue. I am using Zip 0.7 version &  Carthage.
It builds correctly if i build it in my local environment . 

But in my scenario , i am having my own framework with nested frameworks & it supports Gitlab build automation . So whenever a commit happen in my gitlab server , the gitlab runner clones the latest code & tries to built my framework & as well all the dependencies . The built works fine as expected . But if i try to use the built framework, it shows **_missing required module 'minizip'_** . But all other nested frameworks (alamofire ,..) fine except Zip . Am i missing something ?

**Comment by spsammy-symbio** [comment]
I'm having this too.  None of the workaround in the other similar issues are working for me. 

What should I do to be able to check-in the Carthage directory and have it work without having to run carthage update? This is a requirement for our CI and production building process (where we are not allowed to obtain libs external to the network).

**Comment by zhihuitang** [comment]
hi @mostafaberg , I am not using Cocoapod or Carthage. I just added the zip.framework into my Swift demo project. It shows error "** Missing required module 'minizip'** when I tried to build it. Here is the [demo project](https://github.com/zhihuitang/zipdemo)

here is screenshot
https://monosnap.com/file/3n1CdzKhX7VUxEfBJITJsXSvnGjWhy

I found If I ever run&build the zip framework in my Mac, zipdemo project building will succeed. 
Otherwise it shows "**Missing required module 'minizip'** . Just like the problem that guys has in Stackoverflow: https://stackoverflow.com/questions/42085217/swift-project-missing-required-modules-when-import-a-modular-framework

Please help, many thanks to you.

**Comment by 1337mus** [comment]
Having the same issue on Xcode 9.2 using Carthage. Tried updating the Cartfile as mostafaberg mentioned as well as using carthage update --use-submodules no dice :/ Any help appreciated

**Comment by AvdLee** [comment]
This should be fixed with #119.
